const String checkersIphoneHtml = r'''<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>الضامة</title><style>
*{box-sizing:border-box}body{margin:0;padding:14px;background:#101820;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.card{background:#192734;border-radius:20px;padding:14px;margin-bottom:12px}h1{text-align:center;margin:5px}input,button{width:100%;padding:13px;border-radius:13px;font-size:18px;margin-top:8px}button{border:0;background:#d9534f;color:#fff;font-weight:900}.hidden{display:none}.board{display:grid;grid-template-columns:repeat(8,1fr);aspect-ratio:1;border:5px solid #6b4f2a;border-radius:10px;overflow:hidden}.sq{display:flex;align-items:center;justify-content:center;position:relative}.light{background:#ead7b0}.dark{background:#754b2f}.piece{width:72%;height:72%;border-radius:50%;box-shadow:inset 0 0 0 4px #ffffff35,0 3px 5px #0008}.red{background:#d92f3d}.black{background:#16202b;border:2px solid #ddd}.king:after{content:'♛';font-size:24px;color:#ffd166;position:absolute}.selected{outline:4px solid #ffd166;outline-offset:-4px}.target:before{content:'';width:25%;height:25%;border-radius:50%;background:#43d17a;position:absolute}.status{text-align:center;font-size:18px;font-weight:800}.counts{display:flex;gap:8px}.pill{flex:1;text-align:center;background:#26394a;border-radius:12px;padding:8px}
</style></head><body>
<section id="join" class="card"><h1>الضامة</h1><input id="name" placeholder="اسم اللاعب"><button id="joinBtn">دخول كلاعب الأسود</button></section>
<section id="game" class="hidden"><div class="card"><div id="status" class="status">بانتظار المضيف...</div><div class="counts"><div id="red" class="pill"></div><div id="black" class="pill"></div></div></div><div id="board" class="board"></div></section>
<script>
let ws,id,state={};const board=document.getElementById('board');
document.getElementById('joinBtn').onclick=()=>{const name=document.getElementById('name').value.trim();if(!name)return;ws=new WebSocket(`ws://${location.host}/ws`);ws.onopen=()=>ws.send(JSON.stringify({type:'join',name}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='joined'){id=m.id;document.getElementById('join').classList.add('hidden');document.getElementById('game').classList.remove('hidden')}else if(m.type==='state'){state=m;draw()}}};
function draw(){document.getElementById('status').textContent=state.message||'';document.getElementById('red').textContent='الأحمر: '+(state.redCount||0);document.getElementById('black').textContent='الأسود: '+(state.blackCount||0);board.innerHTML='';const targets=new Set(state.targets||[]);(state.board||[]).forEach((row,r)=>row.forEach((p,c)=>{const s=document.createElement('div');s.className='sq '+(((r+c)%2)?'dark':'light');if(state.selected===`${r},${c}`)s.classList.add('selected');if(targets.has(`${r},${c}`))s.classList.add('target');if(p!=='empty'){const d=document.createElement('div');d.className='piece '+(p.startsWith('red')?'red':'black')+(p.endsWith('King')?' king':'');s.appendChild(d)}s.onclick=()=>{if(state.canPlay&&!state.finished)ws.send(JSON.stringify({type:'tap',row:r,col:c}))};board.appendChild(s)}))}
</script></body></html>''';
